[package]
name = "miraplex-utils"
version = "0.0.8"
edition = "2021"
description = "MPL Core Utils library"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/miraland-labs/miraplex-program-library"
license-file = "../../../LICENSE"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"
name = "mpl_utils"

[dependencies]
miraland-program = "=1.14.17-rc5"
borsh = "0.9.3"
arrayref = "0.3.6"
solarti-token = { version = "3.5", features = ["no-entrypoint"], optional = true }

[features]
token = ["solarti-token"]
default = ["token"]

[profile.release]
overflow-checks = true     # Enable integer overflow checks.
